In [283]:
import numpy as np
import pandas as plt
import seaborn as sns
import matplotlib.pyplot as plt

**Linear Regression**

In [312]:
class LinearRegression:
    def __init__(self, epochs, learning_rate):
        self.epochs = epochs
        self.learning_rate = learning_rate
        self.loss = []

    def predict(self, x):
        return np.dot(x, self.w) + self.b

    def fit(self, x, y):
        self.w = np.zeros(x.shape[1])
        self.b = 0

        for i in range(self.epochs):
            y_pred = self.predict(x)
            error = y_pred - y

            """
            Partial derivative
            dError/dW                                       ไส้
                = 2 * (error) * ดิฟไส้   |  diff(x.T * w + b - y) = x.T
                = 2 * (error) * x.T
            """
            grad_w = 2 * np.dot(x.T, error) / len(x)
            grad_b = 2 * np.sum(error) / len(x)

            self.w = self.w - grad_w * self.learning_rate
            self.b = self.b - grad_b * self.learning_rate

            mse = np.mean((error) ** 2)
            self.loss.append(mse)

            if i % 1000 == 0:
                print(f'epoch {i+1}/{self.epochs} loss = {mse}')

    def predict(self, x):
        return np.dot(x, self.w) + self.b

    def get_loss(self):
        return self.loss

    def get_weight(self):
        return self.w

    def get_bias(self):
        return self.b

In [313]:
np.random.seed(12)

x = np.random.rand(3, 3)
y = np.array([i*3 for i in x])

model = LinearRegression(learning_rate=0.01, epochs=10000)
model.fit(x, y)

epoch 1/10000 loss = 3.4981170394239802
epoch 1001/10000 loss = 0.029476569873141338
epoch 2001/10000 loss = 0.017461450686365215
epoch 3001/10000 loss = 0.010524800605339094
epoch 4001/10000 loss = 0.006365133633798873
epoch 5001/10000 loss = 0.0038612405129314947
epoch 6001/10000 loss = 0.002348825171802618
epoch 7001/10000 loss = 0.001432395341520198
epoch 8001/10000 loss = 0.0008754948796695983
epoch 9001/10000 loss = 0.0005361916988130507


In [314]:
pred = model.predict(x)
x, y

(array([[0.15416284, 0.7400497 , 0.26331502],
        [0.53373939, 0.01457496, 0.91874701],
        [0.90071485, 0.03342143, 0.95694934]]),
 array([[0.46248853, 2.22014909, 0.78994505],
        [1.60121818, 0.04372489, 2.75624102],
        [2.70214456, 0.10026428, 2.87084801]]))

In [319]:
pred

array([[0.46146487, 2.21918194, 0.78903014],
       [1.63724609, 0.04991958, 2.73484886],
       [2.6730195 , 0.09510539, 2.8878507 ]])